apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: marjugoncalves/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "src/**/*.js"
          dest: .
    - image: marjugoncalves/comments
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "*.js"
          dest: .
    - image: marjugoncalves/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "*.js"
          dest: .
    - image: marjugoncalves/moderation
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "*.js"
          dest: .
    - image: marjugoncalves/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "*.js"
          dest: .
    - image: marjugoncalves/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "*.js"
          dest: .